name: XMU AutoSignIn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: 30 11 * * *   
  #执行时间在凌晨共执行1次，时间在每天11：30

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install bs4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SignIn
      run: python ./main.py
